services:
  mysql:
    image: mysql
    restart: always
    hostname: ${MYSQL_HOSTNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ../docker-volumes/bff:/var/lib/mysql
