name: CI-Specs

on: [push, pull_request]

jobs:
  specs-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Going to the vault
      run: cd units-vault && ls

    - name: Install make
      run: sudo apt-get install -y make

    - name: Install dependencies
      run: make install

    - name: Run specs
      run: make test