name: CI-CD Units ERP

on:
  push:
    paths:
      - 'units-vault/**'
      - 'units-cashier/**'
      - 'units-bff/**'

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      vault_changed: ${{ steps.filter.outputs.vault }}
      cashier_changed: ${{ steps.filter.outputs.cashier }}
      bff_changed: ${{ steps.filter.outputs.bff }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            vault:
              - 'units-vault/**'
            cashier:
              - 'units-cashier/**'
            bff:
              - 'units-bff/**'


  specs-units-vault:
    if: needs.check-paths.outputs.vault_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: units-vault/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements/base.txt
          python3 -m pip install -r requirements/dev.txt

      - name: Run specs
        run: python3 -m pytest -v

  specs-lint-units-bff:
    if: needs.check-paths.outputs.bff_changed == 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: units-bff/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies from units-bff
        run: yarn

      - name: Run lint from units-bff
        run: yarn lint

      - name: Run specs from units-bff
        run: yarn test

  lint-units-cashier:
     if: needs.check-paths.outputs.cashier_changed == 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: units-cashier/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies from units-cashier
        run: npm install

      - name: Run lint from units-cashier
        run: npm run lint
