name: CI-CD Units ERP

on:
  push:
    paths:
      - 'units-vault/**'
      - 'units-cashier/**'
      - 'units-bff/**'

jobs:
  specs-units-vault:
    if: contains(github.event.head_commit.message, 'units-vault/') || contains(github.event.head_commit.message, 'units-vault/**')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: |
          python3 -m pip install -r units-vault/requirements/base.txt
          python3 -m pip install -r units-vault/requirements/dev.txt

      - name: Run specs
        run: cd units-vault && python3 -m pytest -v

  specs-lint-units-bff:
    if: contains(github.event.head_commit.message, 'units-cashier/') || contains(github.event.head_commit.message, 'units-cashier/**')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies from units-bff
        run: cd units-bff && yarn

      - name: Run lint from units-bff
        run: cd units-bff && yarn lint

      - name: Run specs from units-bff
        run: cd units-bff && yarn test

  lint-units-cashier:
    if: contains(github.event.head_commit.message, 'units-bff/') || contains(github.event.head_commit.message, 'units-bff/**')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies from units-cashier
        run: cd units-cashier && npm install

      - name: Run lint from units-cashier
        run: cd units-cashier && npm run lint
